name: test_ex1
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 3.1.0
  cupertino_icons: ^1.0.8
  flutter_lints: ^6.0.0
  flutter_svg: ^2.2.0
  auto_route: ^10.1.0+1
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  flutter_svg_provider: ^1.0.7
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  path_provider: ^2.1.5
  path: 1.9.1
  collection: ^1.19.1
  bloc: ^9.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  auto_route_generator: ^10.2.3
  freezed: ^3.1.0
  drift_dev: ^2.28.0
  import_sorter: ^4.6.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/presentation/assets/icons/
  fonts:
    - family: Outfit
      fonts:
        - asset: presentation/assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: presentation/assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: presentation/assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: presentation/assets/fonts/Outfit-SemiBold.ttf
          weight: 600
import_sorter:
  emojis: true
  comments: false
  ignored_files:
    - lib/presentation/l10n/*